import 'package:dima_application/generated/flutter-models/AllergenEnum.dart';
import 'package:dima_application/generated/flutter-models/ExerciseFrequency.dart';
import 'package:isar/isar.dart';
import 'package:dima_application/generated/flutter-models/UserDetails.dart';
import 'package:amplify_flutter/amplify_flutter.dart';

part 'user_details_cache.g.dart'; // Generated by Isar

/// Isar model for caching UserDetails from GraphQL
/// 
/// This is a wrapper class that stores the GraphQL UserDetails data
/// with additional caching metadata
@collection
class UserDetailsCache {
  Id id = Isar.autoIncrement; // Auto-increment Isar ID

  /// User ID (mapped from UserDetails.userId)
  @Index(unique: true, replace: true)
  late String userId;

  /// When this cache entry was last fetched from the network
  late DateTime lastFetched;

  // Cache fields from UserDetails
  String? activeMealPlanId;
  List<String>? allergiesJson; // Store as String list since we can't store enums directly
  int? dailyMealsPreference;
  String? exerciseFrequencyString; // Store as String since we can't store enums directly
  double? heightCm;
  String? openTextPreferences;
  String? dietaryRestrictions; 
  String? updatedAtString; // Store as String since we can't store TemporalDateTime
  double? weightKg;
  

  /// Creates a cache entry from a UserDetails object
  static UserDetailsCache fromUserDetails(UserDetails details, DateTime fetchTime) {
    return UserDetailsCache()
      ..userId = details.userId
      ..dietaryRestrictions = details.dietaryRestrictions
      ..lastFetched = fetchTime.toUtc()
      ..activeMealPlanId = details.activeMealPlanId
      ..allergiesJson = details.allergies?.map((e) => e.name).toList()
      ..dailyMealsPreference = details.dailyMealsPreference
      ..exerciseFrequencyString = details.exerciseFrequency.name
      ..heightCm = details.heightCm
      ..openTextPreferences = details.openTextPreferences
      ..updatedAtString = details.updatedAt?.toString()
      ..weightKg = details.weightKg;
  }

  /// Converts this cache entry to a UserDetails object
  UserDetails toUserDetails() {
    return UserDetails(
      userId: userId,
      activeMealPlanId: activeMealPlanId,
      allergies: allergiesJson?.map((e) => AllergenEnum.values.firstWhere(
          (allergen) => allergen.name == e,
          orElse: () => AllergenEnum.values.first)).toList(),
      dailyMealsPreference: dailyMealsPreference!,
      exerciseFrequency: ExerciseFrequency.values.firstWhere(
          (frequency) => frequency.name == exerciseFrequencyString,
          orElse: () => ExerciseFrequency.NOT_SPECIFIED),
      heightCm: heightCm!,
      openTextPreferences: openTextPreferences,
      updatedAt: updatedAtString != null
          ? TemporalDateTime.fromString(updatedAtString!)
          : null,
      weightKg: weightKg!,
      dietaryRestrictions: dietaryRestrictions,
    );
  }
}