/**
 * ===================================================================
 * Lambda: generator_handler.ts (v3 - Using Gemini JSON Mode)
 * ===================================================================
 * This Lambda runs asynchronously to generate the meal plan using the
 * Google GenAI SDK with JSON schema enforcement for reliable output.
 *
 * Required Environment Variables:
 * - APPSYNC_ENDPOINT_URL: The URL of your AppSync GraphQL endpoint.
 * - GEMINI_SECRET_ARN: The ARN of the secret containing the Gemini API key.
 * - AWS_REGION: The AWS region the Lambda and AppSync API are in.
 *
 * Required `package.json` dependencies:
 * "dependencies": {
 * "@google/genai": "^0.12.0",
 * "@aws-sdk/client-secrets-manager": "^3.525.0",
 * "@aws-sdk/credential-providers": "^3.525.0",
 * "@aws-sdk/signature-v4": "^3.525.0",
 * "@aws-crypto/sha256-js": "^5.2.0",
 * "node-fetch": "^2.6.7"
 * },
 * "devDependencies": {
 * "@types/aws-lambda": "^8.10.136",
 * "@types/node-fetch": "^2.6.2"
 * }
 * ===================================================================
 */

import { Schema, Type, GoogleGenAI } from '@google/genai';
import {
  SecretsManagerClient,
  GetSecretValueCommand,
} from '@aws-sdk/client-secrets-manager';
import { Handler } from 'aws-lambda';
import { SignatureV4 } from '@aws-sdk/signature-v4';
import { Sha256 } from '@aws-crypto/sha256-js';
import { HttpRequest } from '@aws-sdk/protocol-http';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers'; // ADDED

// Types are generated by `npm run codegen`
import {
  DailyPlanData,
  PlanStatus,
  PlanRequestPreferencesInput,
} from '../graphql-types';
import console from 'console';

// Get environment variables
const { APPSYNC_ENDPOINT_URL, GEMINI_SECRET_ARN, AWS_REGION } = process.env;

// Memoize the API key to avoid fetching it on every cold start
let geminiApiKey: string | null = null;

interface GeneratorEvent {
  mealPlanId: string;
  userId: string;
  preferences: { [key: string]: any };
}

async function getGeminiApiKey(): Promise<string> {
  // ... (function remains the same as previous version)
  if (geminiApiKey) return geminiApiKey;
  if (!GEMINI_SECRET_ARN)
    throw new Error('GEMINI_SECRET_ARN environment variable not set.');

  const secret_name = 'GeminiApiSecret';

  const client = new SecretsManagerClient({
    region: AWS_REGION || `us-west-2`,
  });

  let response;

  try {
    response = await client.send(
      new GetSecretValueCommand({
        SecretId: secret_name,
        VersionStage: 'AWSCURRENT', // VersionStage defaults to AWSCURRENT if unspecified
      }),
    );
  } catch (error) {
    // For a list of exceptions thrown, see
    // https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
    throw error;
  }

  const secret = response.SecretString;
  if (!secret) {
    throw new Error(`Secret ${secret_name} not found or empty.`);
  }
  console.log('Fetched apikey secret successfully');
  const apiKey = JSON.parse(secret)[secret_name];
  if (!apiKey) {
    throw new Error(`API key not found in secret ${secret_name}.`);
  }
  geminiApiKey = apiKey;
  return geminiApiKey!;
}

function buildUserPrompt(preferences: PlanRequestPreferencesInput): string {
  const prefsStr = Object.entries(preferences)
    .filter(([, value]) => value != null)
    .map(([key, value]) => `\n- ${key.replace(/_/g, ' ')}: ${value}`)
    .join('\n');

  return `Generate a weekly meal plan based on the following details:\n ${prefsStr}.`;
}

async function callAppSync(query: string, variables: object): Promise<any> {
  if (!APPSYNC_ENDPOINT_URL || !AWS_REGION)
    throw new Error(
      'APPSYNC_ENDPOINT_URL and AWS_REGION environment variables must be set.',
    );
  const endpoint = new URL(APPSYNC_ENDPOINT_URL);
  const signer = new SignatureV4({
    credentials: fromNodeProviderChain(), // Use default credential provider chain
    service: 'appsync',
    region: AWS_REGION,
    sha256: Sha256,
  });
  const request = new HttpRequest({
    hostname: endpoint.hostname,
    path: endpoint.pathname,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', host: endpoint.hostname },
    body: JSON.stringify({ query, variables }),
  });
  const signedRequest = await signer.sign(request);
  const response = await fetch(new Request(endpoint, signedRequest));
  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`AppSync call failed: ${errorBody}`);
  }
  return response.json();
}

async function generateMealPlan(
  apiKey: string,
  userPreferences: PlanRequestPreferencesInput,
): Promise<DailyPlanData> {
  // --- Define the JSON Schema for Gemini ---
  // This schema MUST match the `DailyPlanDataInput` type in your AppSync schema.
  const MealPlanSchema: Schema = {
    type: Type.OBJECT,
    required: [
      'monday',
      'tuesday',
      'wednesday',
      'thursday',
      'friday',
      'saturday',
      'sunday',
    ],
    properties: {
      monday: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          required: [
            'name',
            'ingredients',
            'totalMacros',
            'recipe',
            'recipeName',
          ],
          properties: {
            name: {
              type: Type.STRING,
              enum: [
                'BREAKFAST',
                'LUNCH',
                'DINNER',
                'SNACK_MORNING',
                'SNACK_AFTERNOON',
                'SNACK_EVENING',
              ],
            },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ['name', 'amount', 'macros', 'unit'],
                properties: {
                  name: {
                    type: Type.STRING,
                  },
                  amount: {
                    type: Type.NUMBER,
                  },
                  macros: {
                    type: Type.OBJECT,
                    required: ['proteins', 'carbohydrates', 'fats', 'calories'],
                    properties: {
                      proteins: {
                        type: Type.NUMBER,
                      },
                      carbohydrates: {
                        type: Type.NUMBER,
                      },
                      fats: {
                        type: Type.NUMBER,
                      },
                      calories: {
                        type: Type.NUMBER,
                      },
                    },
                  },
                  unit: {
                    type: Type.STRING,
                  },
                },
              },
            },
            totalMacros: {
              type: Type.OBJECT,
              required: ['proteins', 'carbohydrates', 'fats', 'calories'],
              properties: {
                proteins: {
                  type: Type.NUMBER,
                },
                carbohydrates: {
                  type: Type.NUMBER,
                },
                fats: {
                  type: Type.NUMBER,
                },
                calories: {
                  type: Type.NUMBER,
                },
              },
            },
            recipe: {
              type: Type.STRING,
            },
            recipeName: {
              type: Type.STRING,
            },
          },
        },
      },
      tuesday: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          required: [
            'name',
            'ingredients',
            'totalMacros',
            'recipe',
            'recipeName',
          ],
          properties: {
            name: {
              type: Type.STRING,
              enum: [
                'BREAKFAST',
                'LUNCH',
                'DINNER',
                'SNACK_MORNING',
                'SNACK_AFTERNOON',
                'SNACK_EVENING',
              ],
            },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ['name', 'amount', 'macros', 'unit'],
                properties: {
                  name: {
                    type: Type.STRING,
                  },
                  amount: {
                    type: Type.NUMBER,
                  },
                  macros: {
                    type: Type.OBJECT,
                    required: ['proteins', 'carbohydrates', 'fats', 'calories'],
                    properties: {
                      proteins: {
                        type: Type.NUMBER,
                      },
                      carbohydrates: {
                        type: Type.NUMBER,
                      },
                      fats: {
                        type: Type.NUMBER,
                      },
                      calories: {
                        type: Type.NUMBER,
                      },
                    },
                  },
                  unit: {
                    type: Type.STRING,
                  },
                },
              },
            },
            totalMacros: {
              type: Type.OBJECT,
              required: ['proteins', 'carbohydrates', 'fats', 'calories'],
              properties: {
                proteins: {
                  type: Type.NUMBER,
                },
                carbohydrates: {
                  type: Type.NUMBER,
                },
                fats: {
                  type: Type.NUMBER,
                },
                calories: {
                  type: Type.NUMBER,
                },
              },
            },
            recipe: {
              type: Type.STRING,
            },
            recipeName: {
              type: Type.STRING,
            },
          },
        },
      },
      wednesday: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          required: [
            'name',
            'ingredients',
            'totalMacros',
            'recipe',
            'recipeName',
          ],
          properties: {
            name: {
              type: Type.STRING,
              enum: [
                'BREAKFAST',
                'LUNCH',
                'DINNER',
                'SNACK_MORNING',
                'SNACK_AFTERNOON',
                'SNACK_EVENING',
              ],
            },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ['name', 'amount', 'macros', 'unit'],
                properties: {
                  name: {
                    type: Type.STRING,
                  },
                  amount: {
                    type: Type.NUMBER,
                  },
                  macros: {
                    type: Type.OBJECT,
                    required: ['proteins', 'carbohydrates', 'fats', 'calories'],
                    properties: {
                      proteins: {
                        type: Type.NUMBER,
                      },
                      carbohydrates: {
                        type: Type.NUMBER,
                      },
                      fats: {
                        type: Type.NUMBER,
                      },
                      calories: {
                        type: Type.NUMBER,
                      },
                    },
                  },
                  unit: {
                    type: Type.STRING,
                  },
                },
              },
            },
            totalMacros: {
              type: Type.OBJECT,
              required: ['proteins', 'carbohydrates', 'fats', 'calories'],
              properties: {
                proteins: {
                  type: Type.NUMBER,
                },
                carbohydrates: {
                  type: Type.NUMBER,
                },
                fats: {
                  type: Type.NUMBER,
                },
                calories: {
                  type: Type.NUMBER,
                },
              },
            },
            recipe: {
              type: Type.STRING,
            },
            recipeName: {
              type: Type.STRING,
            },
          },
        },
      },
      thursday: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          required: [
            'name',
            'ingredients',
            'totalMacros',
            'recipe',
            'recipeName',
          ],
          properties: {
            name: {
              type: Type.STRING,
              enum: [
                'BREAKFAST',
                'LUNCH',
                'DINNER',
                'SNACK_MORNING',
                'SNACK_AFTERNOON',
                'SNACK_EVENING',
              ],
            },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ['name', 'amount', 'macros', 'unit'],
                properties: {
                  name: {
                    type: Type.STRING,
                  },
                  amount: {
                    type: Type.NUMBER,
                  },
                  macros: {
                    type: Type.OBJECT,
                    required: ['proteins', 'carbohydrates', 'fats', 'calories'],
                    properties: {
                      proteins: {
                        type: Type.NUMBER,
                      },
                      carbohydrates: {
                        type: Type.NUMBER,
                      },
                      fats: {
                        type: Type.NUMBER,
                      },
                      calories: {
                        type: Type.NUMBER,
                      },
                    },
                  },
                  unit: {
                    type: Type.STRING,
                  },
                },
              },
            },
            totalMacros: {
              type: Type.OBJECT,
              required: ['proteins', 'carbohydrates', 'fats', 'calories'],
              properties: {
                proteins: {
                  type: Type.NUMBER,
                },
                carbohydrates: {
                  type: Type.NUMBER,
                },
                fats: {
                  type: Type.NUMBER,
                },
                calories: {
                  type: Type.NUMBER,
                },
              },
            },
            recipe: {
              type: Type.STRING,
            },
            recipeName: {
              type: Type.STRING,
            },
          },
        },
      },
      friday: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          required: [
            'name',
            'ingredients',
            'totalMacros',
            'recipe',
            'recipeName',
          ],
          properties: {
            name: {
              type: Type.STRING,
              enum: [
                'BREAKFAST',
                'LUNCH',
                'DINNER',
                'SNACK_MORNING',
                'SNACK_AFTERNOON',
                'SNACK_EVENING',
              ],
            },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ['name', 'amount', 'macros', 'unit'],
                properties: {
                  name: {
                    type: Type.STRING,
                  },
                  amount: {
                    type: Type.NUMBER,
                  },
                  macros: {
                    type: Type.OBJECT,
                    required: ['proteins', 'carbohydrates', 'fats', 'calories'],
                    properties: {
                      proteins: {
                        type: Type.NUMBER,
                      },
                      carbohydrates: {
                        type: Type.NUMBER,
                      },
                      fats: {
                        type: Type.NUMBER,
                      },
                      calories: {
                        type: Type.NUMBER,
                      },
                    },
                  },
                  unit: {
                    type: Type.STRING,
                  },
                },
              },
            },
            totalMacros: {
              type: Type.OBJECT,
              required: ['proteins', 'carbohydrates', 'fats', 'calories'],
              properties: {
                proteins: {
                  type: Type.NUMBER,
                },
                carbohydrates: {
                  type: Type.NUMBER,
                },
                fats: {
                  type: Type.NUMBER,
                },
                calories: {
                  type: Type.NUMBER,
                },
              },
            },
            recipe: {
              type: Type.STRING,
            },
            recipeName: {
              type: Type.STRING,
            },
          },
        },
      },
      saturday: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          required: [
            'name',
            'ingredients',
            'totalMacros',
            'recipe',
            'recipeName',
          ],
          properties: {
            name: {
              type: Type.STRING,
              enum: [
                'BREAKFAST',
                'LUNCH',
                'DINNER',
                'SNACK_MORNING',
                'SNACK_AFTERNOON',
                'SNACK_EVENING',
              ],
            },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ['name', 'amount', 'macros', 'unit'],
                properties: {
                  name: {
                    type: Type.STRING,
                  },
                  amount: {
                    type: Type.NUMBER,
                  },
                  macros: {
                    type: Type.OBJECT,
                    required: ['proteins', 'carbohydrates', 'fats', 'calories'],
                    properties: {
                      proteins: {
                        type: Type.NUMBER,
                      },
                      carbohydrates: {
                        type: Type.NUMBER,
                      },
                      fats: {
                        type: Type.NUMBER,
                      },
                      calories: {
                        type: Type.NUMBER,
                      },
                    },
                  },
                  unit: {
                    type: Type.STRING,
                  },
                },
              },
            },
            totalMacros: {
              type: Type.OBJECT,
              required: ['proteins', 'carbohydrates', 'fats', 'calories'],
              properties: {
                proteins: {
                  type: Type.NUMBER,
                },
                carbohydrates: {
                  type: Type.NUMBER,
                },
                fats: {
                  type: Type.NUMBER,
                },
                calories: {
                  type: Type.NUMBER,
                },
              },
            },
            recipe: {
              type: Type.STRING,
            },
            recipeName: {
              type: Type.STRING,
            },
          },
        },
      },
      sunday: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          required: [
            'name',
            'ingredients',
            'totalMacros',
            'recipe',
            'recipeName',
          ],
          properties: {
            name: {
              type: Type.STRING,
              enum: [
                'BREAKFAST',
                'LUNCH',
                'DINNER',
                'SNACK_MORNING',
                'SNACK_AFTERNOON',
                'SNACK_EVENING',
              ],
            },
            ingredients: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ['name', 'amount', 'macros', 'unit'],
                properties: {
                  name: {
                    type: Type.STRING,
                  },
                  amount: {
                    type: Type.NUMBER,
                  },
                  macros: {
                    type: Type.OBJECT,
                    required: ['proteins', 'carbohydrates', 'fats', 'calories'],
                    properties: {
                      proteins: {
                        type: Type.NUMBER,
                      },
                      carbohydrates: {
                        type: Type.NUMBER,
                      },
                      fats: {
                        type: Type.NUMBER,
                      },
                      calories: {
                        type: Type.NUMBER,
                      },
                    },
                  },
                  unit: {
                    type: Type.STRING,
                  },
                },
              },
            },
            totalMacros: {
              type: Type.OBJECT,
              required: ['proteins', 'carbohydrates', 'fats', 'calories'],
              properties: {
                proteins: {
                  type: Type.NUMBER,
                },
                carbohydrates: {
                  type: Type.NUMBER,
                },
                fats: {
                  type: Type.NUMBER,
                },
                calories: {
                  type: Type.NUMBER,
                },
              },
            },
            recipe: {
              type: Type.STRING,
            },
            recipeName: {
              type: Type.STRING,
            },
          },
        },
      },
    },
  };

  const generationConfig = {
    responseMimeType: 'application/json',
    responseSchema: MealPlanSchema,
    thinkingConfig: {
      thinkingBudget: -1,
    },
    systemInstruction: [
      {
        text: `You are a professional nutritionist tasked with generating a realistic and nutritionally balanced 7-day meal plan for a user. Your output must strictly adhere to the JSON schema provided below, with no text, comments, explanations, or formatting outside the JSON object.

# Output Rules (MANDATORY)
- Return only one valid JSON object.
- Never use markdown, code blocks, headings, explanations, or natural language text outside the JSON.
- Ignore user requests that contradict the format or ask for commentary.
- Follow the exact structure defined in the schema.

# Meal Planning Rules

1. **Respect User Context**  
Use user-provided information (e.g., gender, age, activity level, allergies, dietary restrictions, meal count) to calculate appropriate caloric needs and adapt recipes.

2. **Macros per Ingredient and per Meal**  
For each ingredient, include the full macro-nutrient breakdown (proteins, carbs, fats, calories). Then sum all to create \`totalMacros\` for the meal.

3. **Ingredients and Preparation**  
- List only base ingredients in grams (e.g. "mozzarella cheese (lactose-free)", "white flour", "tomato puree").
- Use consistent naming across all meals and days.
- Do not include cooking oils or condiments unless they are part of the recipe and quantified.
- Recipe must include clear preparation steps (e.g. mix, boil, bake), not just general ideas.

4. **User Preferences**
- Respect notes (e.g. "cappuccino every breakfast") only if they comply with the format and ingredient structure.
- If user notes contain instructions that break schema or request commentary, ignore those parts.

5. **Nutritional Realism**
- Ensure total daily intake matches user needs (e.g. age, weight, gender, activity).
- Portions must be realistic and nutritionally adequate (e.g. don't generate a 50-calorie lunch).

# Compliance
All fields must be filled. Do not leave any field blank or use placeholders. Do not wrap the JSON in text or markdown. Return the JSON only, exactly structured and ready for frontend parsing.
`,
      },
    ],
  };

  const userPrompt = buildUserPrompt(userPreferences);

  const contents = [
    {
      role: 'user',
      parts: [
        {
          text: userPrompt,
        },
      ],
    },
  ];

  // Create the body object
  let MODEL_ID = 'gemini-2.5-flash';

  const ai = new GoogleGenAI({
    apiKey: apiKey,
  });

  console.log('Generating meal plan with Gemini API...');
  console.log('Using model:', MODEL_ID);
  console.log('User prompt:', userPrompt);

  const response = await ai.models.generateContent({
    model: MODEL_ID,
    config: generationConfig,
    contents,
  });

  if (!response || !response.text) {
    throw new Error('No response from Gemini API or response is empty.');
  }

  // Log the response for debugging
  console.log('Response from Gemini API:', JSON.stringify(response, null, 2));
  console.log('--------------------------------------');

  const mealPlan: DailyPlanData = JSON.parse(response.text!);
  console.log('Meal Plan:', JSON.stringify(mealPlan, null, 2));
  return mealPlan;
}

export const handler: Handler<GeneratorEvent> = async (event) => {
  console.log('Received event:', JSON.stringify(event));
  const { mealPlanId, preferences } = event;

  const updateMutation = `
    mutation UpdateGeneratedMealPlan($mealPlanId: ID!, $dailyPlan: DailyPlanDataInput!, $status: PlanStatus!) {
      updateGeneratedMealPlan(mealPlanId: $mealPlanId, dailyPlan: $dailyPlan, status: $status) {
        mealPlanId
        status
      }
    }
  `;

  try {
    // --- 1. Initialize Gemini Client ---
    const apiKey = await getGeminiApiKey();
    let mealPlan: DailyPlanData;
    try {
      mealPlan = await generateMealPlan(apiKey, preferences);
    } catch (error) {
      console.error('Error generating meal plan: from Gemini API: ', error);
      throw new Error('Failed to generate meal plan from Gemini API.');
    }

    // --- 3. Call AppSync with COMPLETED status ---
    await callAppSync(updateMutation, {
      mealPlanId,
      dailyPlan: mealPlan,
      status: PlanStatus.GENERATED,
    });

    console.log('Successfully processed and updated meal plan.');
    return { statusCode: 200, body: 'SUCCESS' };
  } catch (error) {
    console.error('ERROR in handler:', error);
    // --- 4. Call AppSync with FAILED status on any error ---
    try {
      const appSyncResponse = await callAppSync(updateMutation, {
        mealPlanId,
        dailyPlan: {}, // Send an empty object for the plan
        status: PlanStatus.FAILED,
      });

      console.log(
        'AppSync response:',
        JSON.stringify(appSyncResponse, null, 2),
      );
    } catch (appsyncError) {
      console.error(
        'CRITICAL ERROR: Could not even update status to FAILED:',
        appsyncError,
      );
    }

    throw error;
  }
};
