// Mocks generated by Mockito 5.4.4 from annotations
// in dima_application/test/unit/services/nutritionist_location_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:amplify_flutter/amplify_flutter.dart' as _i2;
import 'package:dima_application/AmplifyWrapper/AmplifyGraphQL.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGraphQLOperation_0<T1> extends _i1.SmartFake
    implements _i2.GraphQLOperation<T1> {
  _FakeGraphQLOperation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AmplifyGraphQL].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmplifyGraphQL extends _i1.Mock implements _i3.AmplifyGraphQL {
  @override
  _i2.GraphQLOperation<T> query<T>({required _i2.GraphQLRequest<T>? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [],
          {#request: request},
        ),
        returnValue: _FakeGraphQLOperation_0<T>(
          this,
          Invocation.method(
            #query,
            [],
            {#request: request},
          ),
        ),
        returnValueForMissingStub: _FakeGraphQLOperation_0<T>(
          this,
          Invocation.method(
            #query,
            [],
            {#request: request},
          ),
        ),
      ) as _i2.GraphQLOperation<T>);

  @override
  _i2.GraphQLOperation<T> mutate<T>(
          {required _i2.GraphQLRequest<T>? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #mutate,
          [],
          {#request: request},
        ),
        returnValue: _FakeGraphQLOperation_0<T>(
          this,
          Invocation.method(
            #mutate,
            [],
            {#request: request},
          ),
        ),
        returnValueForMissingStub: _FakeGraphQLOperation_0<T>(
          this,
          Invocation.method(
            #mutate,
            [],
            {#request: request},
          ),
        ),
      ) as _i2.GraphQLOperation<T>);

  @override
  _i4.Stream<_i2.GraphQLResponse<T>> subscribe<T>(
    _i2.GraphQLRequest<T>? request, {
    void Function()? onEstablished,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribe,
          [request],
          {#onEstablished: onEstablished},
        ),
        returnValue: _i4.Stream<_i2.GraphQLResponse<T>>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.GraphQLResponse<T>>.empty(),
      ) as _i4.Stream<_i2.GraphQLResponse<T>>);
}
