// Mocks generated by Mockito 5.4.4 from annotations
// in dima_application/test/unit/services/image_upload_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:amplify_flutter/amplify_flutter.dart' as _i2;
import 'package:dima_application/AmplifyWrapper/AmplifyAuth.dart' as _i3;
import 'package:dima_application/AmplifyWrapper/AmplifyStorage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthSession_0 extends _i1.SmartFake implements _i2.AuthSession {
  _FakeAuthSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthUser_1 extends _i1.SmartFake implements _i2.AuthUser {
  _FakeAuthUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageUploadDataResult_2<Item extends _i2.StorageItem>
    extends _i1.SmartFake implements _i2.StorageUploadDataResult<Item> {
  _FakeStorageUploadDataResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageGetUrlResult_3 extends _i1.SmartFake
    implements _i2.StorageGetUrlResult {
  _FakeStorageGetUrlResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageRemoveResult_4<Item extends _i2.StorageItem>
    extends _i1.SmartFake implements _i2.StorageRemoveResult<Item> {
  _FakeStorageRemoveResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AmplifyAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmplifyAuth extends _i1.Mock implements _i3.AmplifyAuth {
  MockAmplifyAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthSession> fetchAuthSession() => (super.noSuchMethod(
        Invocation.method(
          #fetchAuthSession,
          [],
        ),
        returnValue: _i4.Future<_i2.AuthSession>.value(_FakeAuthSession_0(
          this,
          Invocation.method(
            #fetchAuthSession,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AuthSession>);

  @override
  _i4.Future<_i2.AuthUser> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.AuthUser>.value(_FakeAuthUser_1(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AuthUser>);

  @override
  _i4.Future<List<_i2.AuthUserAttribute>> fetchUserAttributes() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserAttributes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.AuthUserAttribute>>.value(
            <_i2.AuthUserAttribute>[]),
      ) as _i4.Future<List<_i2.AuthUserAttribute>>);

  @override
  _i4.Future<void> updateUserAttributes(
          List<_i2.AuthUserAttribute>? attributes) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserAttributes,
          [attributes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signUp(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(
    String? oldPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [
            oldPassword,
            newPassword,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void listen(void Function(_i2.AuthHubEvent)? handleAuthEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #listen,
          [handleAuthEvent],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AmplifyStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmplifyStorage extends _i1.Mock implements _i5.AmplifyStorage {
  MockAmplifyStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StorageUploadDataResult<_i2.StorageItem>> uploadData({
    required _i2.StorageDataPayload? data,
    required _i2.StoragePath? path,
    _i2.StorageUploadDataOptions? options =
        const _i2.StorageUploadDataOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadData,
          [],
          {
            #data: data,
            #path: path,
            #options: options,
          },
        ),
        returnValue:
            _i4.Future<_i2.StorageUploadDataResult<_i2.StorageItem>>.value(
                _FakeStorageUploadDataResult_2<_i2.StorageItem>(
          this,
          Invocation.method(
            #uploadData,
            [],
            {
              #data: data,
              #path: path,
              #options: options,
            },
          ),
        )),
      ) as _i4.Future<_i2.StorageUploadDataResult<_i2.StorageItem>>);

  @override
  _i4.Future<_i2.StorageGetUrlResult> getUrl({
    required _i2.StoragePath? path,
    _i2.StorageGetUrlOptions? options = const _i2.StorageGetUrlOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUrl,
          [],
          {
            #path: path,
            #options: options,
          },
        ),
        returnValue: _i4.Future<_i2.StorageGetUrlResult>.value(
            _FakeStorageGetUrlResult_3(
          this,
          Invocation.method(
            #getUrl,
            [],
            {
              #path: path,
              #options: options,
            },
          ),
        )),
      ) as _i4.Future<_i2.StorageGetUrlResult>);

  @override
  _i4.Future<_i2.StorageRemoveResult<_i2.StorageItem>> remove(
          {required _i2.StoragePath? path}) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
          {#path: path},
        ),
        returnValue: _i4.Future<_i2.StorageRemoveResult<_i2.StorageItem>>.value(
            _FakeStorageRemoveResult_4<_i2.StorageItem>(
          this,
          Invocation.method(
            #remove,
            [],
            {#path: path},
          ),
        )),
      ) as _i4.Future<_i2.StorageRemoveResult<_i2.StorageItem>>);
}
